### ISSUE TITLE
[Android Training] Prework: SimpleTodo - Ready for Review

### ISSUE THREAD

**Issue by allench** [allench/android-app-prework#1]
Hello, my prework app is complete, please help review. /cc @codepathreview @codepath
## Thanks!

Allen Chiang

**Comment by nidhi1608** [comment]
Looks great! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.
Nice job with the project, hope you found it as a helpful introduction and see you on Friday!

**Comment by allench** [comment]
Thank you!
